paired: true
reference: /media/biolinux/Data/Astrid_RADseq_data/ref_genome_HV/HV_genome_6_dec
samples:
    forward: /media/biolinux/Data/Astrid_RADseq_data/sub_forward.fq.gz
    reverse: /media/biolinux/Data/Astrid_RADseq_data/sub_reverse.fq.gz
barcodes: /media/biolinux/Data/Astrid_RADseq_data/barcodes.csv
popmap: /media/biolinux/Data/Astrid_RADseq_data/Popmap_4_dec.txt

